version: '3'

services:
  app:
    image: nifisample/app
    links:
      - app-postgre-db:app-postgre-db
    ports:
      - 80:80

  app-postgre-db:
    image: nifisample/postgre-sql
    volumes:
      - NiFiSamplePostgreDb:/var/lib/pgsql/data/

  apache-nifi:
    image: apache/nifi
    ports:
      - 8443:8443

volumes:
  NiFiSamplePostgreDb:
